You are given an array prices where `prices[i]` is the price of a given stock on the `i`th day.

You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

---

So, left-to-right, we are looking for the largest difference between right-hand term and left-hand term.

Should be able to do this in $O(n)$ time and $O(1)$ space.

In [1]:
def maxProfit(prices: list[int]) -> int:
    pass

In [5]:
prices = [1, 2, 3, 5, 2, 7]
7-1

6

In [6]:
def maxProfit(prices: list[int]) -> int:
    max_price = float('inf')
    min_price = -1

    

No wait, due to the constaint of left-to-right we can't just subtract max and min.

My first thought of a shortcut (min from left, max from right, meet in middle) also doesn't work because what if both min and max are on the last two days sequentially (respectively).

Hmmm

---

## Brute force: 
$O(n^2)$ time and $O(1)$ space

In [8]:
def maxProfit(prices: list[int]) -> int:
    max_price = float('inf')
    min_price = -1

In [9]:
prices

[1, 2, 3, 5, 2, 7]

In [11]:
import numpy as np

In [12]:
np.argmax(prices)

5

In [13]:
arr = prices.copy()

In [14]:
arr

[1, 2, 3, 5, 2, 7]

In [16]:
arr

[1, 2, 3, 5, 2, 7]

In [17]:
prices

[1, 2, 3, 5, 2, 7]

In [18]:
prices[0] = [0]

In [19]:
prices

[[0], 2, 3, 5, 2, 7]

In [20]:
prices[0] = 0

In [21]:
prices

[0, 2, 3, 5, 2, 7]

In [22]:
arr

[1, 2, 3, 5, 2, 7]

In [23]:
arr = np.array(arr)

In [24]:
arr

array([1, 2, 3, 5, 2, 7])

In [25]:
arr.argsort()

array([0, 1, 4, 2, 3, 5])

In [27]:
arr

array([1, 2, 3, 5, 2, 7])

In [28]:
print(arr)
print(arr.argsort())

[1 2 3 5 2 7]
[0 1 4 2 3 5]


---

Ok, so just doing an argsort is $O(n log n)$ and $O(1)$ space complexity.

Argsort takes in a list and stores the indices of that list which would sort the array, so it's just a sort algorithm which stores the translation of input -> sorted and not the sorted array itself.

Since the indices maintain order from original, we can check them for correct order (left-right position) and return the correct result as follows:

In [29]:
def maxProfit(prices: list[int]) -> int:
    L = np.array(prices)
    L_argsorted = L.argsort()

    for i, j in zip(L_argsorted, L_argsorted[::-1]):
        if i >= j:
            return 0
        print(i, j)
        

In [30]:
maxProfit(arr)

0 5
1 3
4 2
2 4
3 1
5 0


In [31]:
for i, prices in enumerate(zip(prices, prices[::-1])):
    ...:     print(i, prices)

0 (0, 7)
1 (2, 2)
2 (3, 5)
3 (5, 3)
4 (2, 2)
5 (7, 0)


This is stupid, there's definitely just a way to do this in O(n) with 2 pointers like they want.

Just have it start in middle and iterate outwards.

----

In [23]:
def maxProfit(prices: list[int]) -> int:
    n = len(prices)
    i, j = 0, 1
    max_profit = 0
    
    while j < n:
        profit = prices[j] - prices[i]
        max_profit = max(profit, max_profit)
        if prices[i] > prices[j]:
            i = j
        j += 1
    return max_profit


In [24]:
prices = [7,1,5,3,6,4]
maxProfit(prices)

5